build and push image:
  image: docker:latest
  stage: build
  only:
    - tags
  services:
  - name: docker:dind
    command: ["--experimental"]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
    BUILDX_PLATFORM: linux/amd64,linux/arm64
  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker buildx install
    - docker info
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u "$DOCKER_REGISTRY_USER" $DOCKER_REGISTRY --password-stdin
    - apk update
    - apk upgrade
    - apk add --update --no-cache build-base python3 python3-dev libffi-dev openssl-dev py-pip bash
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker tag knobik/rpicloud knobik/rpicloud:$CI_COMMIT_TAG
    - docker push knobik/rpicloud
