version: '3.4'
services:
  rpicloud-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
    volumes:
      - ./.docker/config/dnsmasq:/etc/dnsmasq.d/
      - ./.docker/config/nginx/virtualhosts:/etc/nginx/sites-enabled
      - ./web:/web
      - ./api:/api
      - ./.data:/.data
#      - ./.data/nfs/boot:/nfs/boot
#      - ./.data/nfs/root:/nfs/root
      - ./backups:/nfs/backups
    network_mode: "host"
    privileged: true
