version: '3'
services:
  rpi-cluster-pxe:
    build:
      context: .docker
      dockerfile: Dockerfile
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
    volumes:
      - ./.docker/config/dnsmasq:/etc/dnsmasq.d/
      - ./.docker/config/nginx:/etc/nginx/sites-enabled
      - ./src:/var/www/html
      - ./baseImage:/nfs
    network_mode: "host"
